export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',
  SUPER_ADMIN_PHONE = 'SUPER_ADMIN_PHONE',
  SUPER_ADMIN_EMPLOYEE_ID = 'SUPER_ADMIN_EMPLOYEE_ID',

  REDIS_URL = 'REDIS_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  TELNYX_API_KEY = 'TELNYX_API_KEY',
  TELNYX_PHONE_NUMBER = 'TELNYX_PHONE_NUMBER',
  TELNYX_ALPHA_SENDER = 'TELNYX_ALPHA_SENDER',
  TELNYX_MESSAGING_PROFILE_ID = 'TELNYX_MESSAGING_PROFILE_ID',

  APPLE_REVIEW_EMAIL = 'APPLE_REVIEW_EMAIL',
  APPLE_REVIEW_OTP = 'APPLE_REVIEW_OTP',
}
